version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REALIZATION=${REALIZATION}
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./sources:/app/sources
